### PR TITLE
Add centos7 builds

### LINKED ISSUE #10: Build also for centos7
Apparently there is a need for centos7.
I'm hacking into it.

### PR DESCRIPTION
**Pull request by marcvs**
Fix #10

### CODE REVIEW

**Comment by dianagudu** [comment]
`nginx` dependency cannot be met, requires `epel-release`

**Comment by dianagudu** [comment]
With epel-release installed, the package installs, but the service fails to start with:
```
Traceback (most recent call last):
...
  File "/usr/lib/motley-cue/lib/python3.6/site-packages/motley_cue/api.py", line 1, in <module>
    from fastapi import FastAPI, Depends, Request
  File "/usr/lib/motley-cue/lib/python3.6/site-packages/fastapi/__init__.py", line 7, in <module>
    from .applications import FastAPI as FastAPI
  File "/usr/lib/motley-cue/lib/python3.6/site-packages/fastapi/applications.py", line 3, in <module>
    from fastapi import routing
  File "/usr/lib/motley-cue/lib/python3.6/site-packages/fastapi/routing.py", line 18, in <module>
    from fastapi import params
  File "/usr/lib/motley-cue/lib/python3.6/site-packages/fastapi/params.py", line 4, in <module>
    from pydantic.fields import FieldInfo
  File "pydantic/__init__.py", line 2, in init pydantic.__init__
  File "pydantic/dataclasses.py", line 3, in init pydantic.dataclasses
  File "pydantic/class_validators.py", line 8, in init pydantic.class_validators
  File "pydantic/errors.py", line 5, in init pydantic.errors
  File "pydantic/typing.py", line 23, in init pydantic.typing
ModuleNotFoundError: No module named 'typing_extensions'
```
Could be related to python version, might need to add `typing_extensions` as requirement for python <3.7

[typing_extensions](https://pypi.org/project/typing-extensions/):

> Typing Extensions – Backported and Experimental Type Hints for Python
> 
> The typing module was added to the standard library in Python 3.5 on a provisional basis and will no longer be provisional in Python 3.7. However, this means users of Python 3.5 - 3.6 who are unable to upgrade will not be able to take advantage of new types added to the typing module, such as typing.Text or typing.Coroutine.
> 
> The typing_extensions module contains both backports of these changes as well as experimental types that will eventually be added to the typing module, such as Protocol or TypedDict.
> 
> Users of other Python versions should continue to install and use the typing module from PyPi instead of using this one unless specifically writing code that must be compatible with multiple Python versions or requires experimental types.

**Comment by marcvs** [comment]
I'll dive into this today

**Comment by marcvs** [comment]
Were you able to test this inside a docker, or did you install a VM?

**Comment by dianagudu** [comment]
I installed a VM, since systemd does not work inside a container.

**Comment by marcvs** [comment]
Should work, please verify

**Pull request merged**
