### PR TITLE
add opensuse-15.2 and opensuse_tumbleweed

### PR DESCRIPTION
**Pull request by marcvs**
:)

### CODE REVIEW

**Comment by marcvs** [comment]
Now I should be done here.

**Comment by dianagudu** [comment]
So far, tested on:
* opensuse 15.2: works (after updating running requirements in cbe02bfa21b078af2cb838109f339fbad3a49440)
* opensuse tumbleweed: python links not fully adjusted:
  * on install: `Package was packed for python3.8 adjusting symlinks for installed python3.7`
  * lib folder link adjusted: `/usr/lib/motley-cue/lib/python3.7 -> /usr/lib/motley-cue/lib/python3.8`
  * however, python executable still points to different version not present on the system:
` /usr/lib/motley-cue/bin/python -> /usr/bin/python3.8`

**Comment by marcvs** [comment]
> So far, tested on:
> 
>     * opensuse 15.2: works (after updating running requirements in [cbe02bf](https://github.com/dianagudu/motley_cue/commit/cbe02bfa21b078af2cb838109f339fbad3a49440))
> 
>     * opensuse tumbleweed: python links not fully adjusted:
>       
>       * on install: `Package was packed for python3.8 adjusting symlinks for installed python3.7`
>       * lib folder link adjusted: `/usr/lib/motley-cue/lib/python3.7 -> /usr/lib/motley-cue/lib/python3.8`
>       * however, python executable still points to different version not present on the system:
>         ` /usr/lib/motley-cue/bin/python -> /usr/bin/python3.8`

Strange. This is how it looks for me:
```
root@susetw:~# rpm -i motley-cue-0.1.1-1.x86_64.rpm 
For loop: PYTHONDIR: python3.8
PKG_PYTHONDIR: python3.8
/var/tmp/rpm-tmp.nqqr2h: line 35: semodule: command not found
/var/tmp/rpm-tmp.nqqr2h: line 36: semodule: command not found
/var/tmp/rpm-tmp.nqqr2h: line 37: semodule: command not found
/var/tmp/rpm-tmp.nqqr2h: line 38: setsebool: command not found
Created symlink /etc/systemd/system/multi-user.target.wants/motley-cue.service → /lib/systemd/system/motley-cue.service.
Created symlink /etc/systemd/system/multi-user.target.wants/nginx.service → /usr/lib/systemd/system/nginx.service.
root@susetw:~# cd /usr/lib/motley-cue/lib
root@susetw:/usr/lib/motley-cue/lib# ls
python3.8/
root@susetw:/usr/lib/motley-cue/lib# cd ../bin/
root@susetw:/usr/lib/motley-cue/bin# ls -l python*
lrwxrwxrwx 1 root root 18 May 12 13:57 python -> /usr/bin/python3.8*
lrwxrwxrwx 1 root root  6 May 12 13:57 python3 -> python*
lrwxrwxrwx 1 root root  6 May 12 13:57 python3.8 -> python*
```
I.e. I'll have to remove the selinux commands and then should be fine.

**Comment by marcvs** [comment]
Please retry with this rpm:
http://marcus.hardt-it.de/motley-cue-0.1.1-1.x86_64.rpm

**Comment by dianagudu** [comment]
It works now. It was actually an issue with the image I used for the VM and not properly updating via `zypper dup`, so my python version was 3.7.

**Comment by marcvs** [comment]
Ok; So this one can be merged.

I got comments on pam-ssh-oidc that I'll fix.

RPM build will see fundamental changes, but I'll develop them on pam-ssh-oidc first

**Pull request merged**
