### PR TITLE
add call to flaat.get_issuer_from_accesstoken()

### PR DESCRIPTION
**Pull request by marcvs**
Requires latest flaat from `add-issuer-retriever` branch

### CODE REVIEW

**Comment by marcvs** [comment]
It's now published with flaat 0.14.4

Please test carefully, as I did quite some changes regardig caching (mostly in vain, though)

**Comment by dianagudu** [comment]
Thanks! I am currently testing this.

**Comment by marcvs** [comment]
Sorry, I merged by error. 

It should work though

**Comment by dianagudu** [comment]
I am getting an error with the new flaat:
```
ModuleNotFoundError: No module named 'logsetup'
```

**Pull request merged**
